import React from 'react';
import AnimatedPage from "./AnimatedPage";
import Ononoki from '/src/components/Ononoki';
// import "./pages.css";

const OnonokiPage = () => {
  return (
    <AnimatedPage>
        <div style={{
            justifyContent: 'centre',
            alignItems: 'centre',
            fontSize:"30px",
        }}
        >
        <h1 class="centerheader">Welcome to the secret Ononoki page :)</h1>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        <Ononoki/>
        </div>
    </AnimatedPage>
  );
};

export default OnonokiPage;